# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QMainWindow(object):
    def setupUi(self, QMainWindow):
        QMainWindow.setObjectName("QMainWindow")
        QMainWindow.resize(342, 267)
        self.centralwidget = QtWidgets.QWidget(QMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.inputHipo = QtWidgets.QLineEdit(self.centralwidget)
        self.inputHipo.setObjectName("inputHipo")
        self.gridLayout.addWidget(self.inputHipo, 0, 2, 1, 1)
        self.inputCateto1 = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCateto1.setObjectName("inputCateto1")
        self.gridLayout.addWidget(self.inputCateto1, 1, 2, 1, 1)
        self.Resultado = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Resultado.setFont(font)
        self.Resultado.setMouseTracking(True)
        self.Resultado.setObjectName("Resultado")
        self.Resultado.setDisabled(True)


        self.gridLayout.addWidget(self.Resultado, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.inputCateto2 = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCateto2.setObjectName("inputCateto2")
        self.gridLayout.addWidget(self.inputCateto2, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.display = QtWidgets.QLineEdit(self.centralwidget)
        self.display.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.display.setFont(font)
        self.display.setObjectName("display")
        self.gridLayout.addWidget(self.display, 3, 2, 1, 1)
        self.calcular = QtWidgets.QPushButton(self.centralwidget)
        self.calcular.setObjectName("calcular")
        self.gridLayout.addWidget(self.calcular, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        QMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(QMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)

    def retranslateUi(self, QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        QMainWindow.setWindowTitle(_translate("QMainWindow", "Pitagoras"))
        self.label.setText(_translate("QMainWindow", "Hipotenusa"))
        self.label_2.setText(_translate("QMainWindow", "Cateto1"))
        self.label_3.setText(_translate("QMainWindow", "Cateto2"))
        self.label_4.setText(_translate("QMainWindow", "Resultado"))
        self.calcular.setText(_translate("QMainWindow", "Calcular"))
        self.label_5.setText(_translate("QMainWindow", "EQUAÇÃO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QMainWindow = QtWidgets.QMainWindow()
    ui = Ui_QMainWindow()
    ui.setupUi(QMainWindow)
    QMainWindow.show()
    sys.exit(app.exec_())
